"""init: all tables

Revision ID: 86a6d5bc6f70
Revises: 
Create Date: 2023-12-09 01:17:53.391949

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86a6d5bc6f70"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("characteristic_name_key", "characteristic", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("characteristic_name_key", "characteristic", ["name"])
    # ### end Alembic commands ###
